from turtle import *

my_turtle = Turtle()
my_turtle.speed(0)
my_turtle.screen.setup(800, 600)

my_turtle.penup()
my_turtle.goto(0, -100)
my_turtle.pendown()
my_turtle.circle(100)

my_turtle.penup()
my_turtle.goto(-50, 50)
my_turtle.pendown()
my_turtle.setheading(60)
my_turtle.forward(100)
my_turtle.setheading(180)
my_turtle.circle(-30, 120)
my_turtle.setheading(60)
my_turtle.forward(100)

my_turtle.penup()
my_turtle.goto(50, 50)
my_turtle.pendown()
my_turtle.setheading(120)
my_turtle.forward(100)
my_turtle.setheading(0)
my_turtle.circle(30, 120)
my_turtle.setheading(120)
my_turtle.forward(100)

my_turtle.penup()
my_turtle.goto(-30, 0)
my_turtle.pendown()
my_turtle.circle(15)

my_turtle.penup()
my_turtle.goto(30, 0)
my_turtle.pendown()
my_turtle.circle(15)

my_turtle.penup()
my_turtle.goto(0, -30)
my_turtle.pendown()
my_turtle.setheading(270)
my_turtle.forward(20)
my_turtle.setheading(0)
my_turtle.circle(20, 180)
my_turtle.setheading(90)
my_turtle.forward(20)

my_turtle.penup()
my_turtle.goto(-30, -30)
my_turtle.pendown()
my_turtle.setheading(225)
my_turtle.forward(60)

my_turtle.penup()
my_turtle.goto(-30, -40)
my_turtle.pendown()
my_turtle.setheading(240)
my_turtle.forward(60)

my_turtle.penup()
my_turtle.goto(-30, -50)
my_turtle.pendown()
my_turtle.setheading(255)
my_turtle.forward(60)

my_turtle.penup()
my_turtle.goto(30, -30)
my_turtle.pendown()
my_turtle.setheading(315)
my_turtle.forward(60)

my_turtle.penup()
my_turtle.goto(30, -40)
my_turtle.pendown()
my_turtle.setheading(300)
my_turtle.forward(60)

my_turtle.penup()
my_turtle.goto(30, -50)
my_turtle.pendown()
my_turtle.setheading(285)
my_turtle.forward(60)

my_turtle.penup()
my_turtle.goto(0, -150)
my_turtle.screen.exitonclick()
my_turtle.screen.mainloop()